"""Canonical College assistant acceptance questions supplied by the product owner."""

COLLEGE_QUESTIONS = (
    "Show me the complete profile of this student.",
    "What is this student's current CGPA?",
    "What is this student's attendance percentage?",
    "Which department and class does this student belong to?",
    "Show me this student's semester-wise academic performance.",
    "What certifications does this student have?",
    "What technical skills does this student have?",
    "What projects has this student completed?",
    "Has this student participated in any internships?",
    "Has this student been placed yet?",
    "Show all students in 3rd-year CSE.",
    "Show students with CGPA above 8.",
    "Show students with attendance below 75%.",
    "Find students who scored below 50% in Mathematics.",
    "Find students who have not completed their profile.",
    "Show students who have completed an internship.",
    "Find students who know Python and Java.",
    "Show students with more than three certifications.",
    "Find students who have not attended any placement training.",
    "Show students who are currently unplaced.",
    "Compare the academic performance of these two students.",
    "Who has the higher CGPA between these two students?",
    "Compare the attendance of these students.",
    "Compare their semester-wise performance.",
    "Which student has improved more over the last two semesters?",
    "Who has better placement readiness?",
    "Compare their technical skills.",
    "Compare their certifications and projects.",
    "Who has better attendance and academic performance overall?",
    "Which student is a better match for this company's requirements?",
    "Who are the top 10 students in CSE by CGPA?",
    "Who are the top 10 students in the college by academic performance?",
    "Rank students based on placement readiness.",
    "Rank students based on attendance.",
    "Rank students based on technical skills.",
    "Who are the top-performing students in this class?",
    "Who are the most improved students this semester?",
    "Which students have the highest number of certifications?",
    "Which students have the strongest project portfolios?",
    "Who are the top students eligible for the upcoming placement drive?",
    "Which class has the highest average attendance?",
    "Which class has the lowest attendance?",
    "Compare attendance between CSE A and CSE B.",
    "Compare attendance between two departments.",
    "Which students have attendance below 60%?",
    "Which students have shown a sudden drop in attendance?",
    "Which students have consistently maintained attendance above 90%?",
    "Which subjects have the lowest attendance?",
    "Which class has the highest number of students below 75% attendance?",
    "Is there a relationship between attendance and academic performance?",
    "Compare CSE A and CSE B based on average CGPA.",
    "Compare CSE A and CSE B based on attendance.",
    "Which class performed better in the last semester?",
    "Which class has more students above 8 CGPA?",
    "Which class has more academically weak students?",
    "Compare the placement performance of two classes.",
    "Which class has better technical skills?",
    "Compare the number of certifications between two classes.",
    "Which class has better internship participation?",
    "Give me an overall comparison of these two classes.",
    "Which department has the highest average CGPA?",
    "Compare CSE, IT, ECE, and EEE based on academic performance.",
    "Which department has the highest placement percentage?",
    "Which department has the highest average package?",
    "Which department has the highest attendance?",
    "Which department has the most students eligible for placements?",
    "Compare the number of certifications across departments.",
    "Which department has the strongest technical skill profile?",
    "Which department improved the most compared with last year?",
    "Give me an overall performance comparison of all departments.",
    "Which subjects have the highest failure rate?",
    "Which subject is students' weakest overall?",
    "Which class performed best in Data Structures?",
    "Compare Mathematics performance between CSE A and CSE B.",
    "Which department has the highest average score in Python?",
    "Which students are consistently weak in core subjects?",
    "Which students improved the most in their difficult subjects?",
    "Compare this semester's results with the previous semester.",
    "Which subjects show the biggest improvement?",
    "Which classes need additional academic support?",
    "Which companies have recruited students from our college?",
    "Which company recruited the highest number of students?",
    "Which company offered the highest package?",
    "Compare Infosys and TCS based on number of selections.",
    "Compare companies based on average package offered.",
    "Which companies are recruiting the most students from CSE?",
    "Which companies have the highest eligibility criteria?",
    "Which students are eligible for this company's drive?",
    "Which eligible students have not applied for this company?",
    "Which students are the best matches for this company's job requirements?",
    "Compare the students selected by Infosys and TCS.",
    "What skills are common among students selected by high-paying companies?",
    "What is different between students selected and students not selected?",
    "Which students have skills similar to those hired by this company?",
    "Which department has the highest success rate for this company?",
    "Which companies are the best match for our students' current skill profiles?",
    "What skills are most commonly missing among students who were not selected?",
    "Which students have high CGPA but are still unplaced?",
    "Which students have average CGPA but strong placement performance?",
    "Analyze our placement data and tell me what factors appear to contribute most to successful placements.",
    "Which students are eligible for the upcoming placement drive?",
    "Show students who are eligible for at least 5 companies.",
    "Which students are eligible for the most number of companies?",
    "Which students are not eligible for any current placement drives?",
    "Compare placement eligibility between CSE A and CSE B.",
    "Which department has the highest placement eligibility rate?",
    "Which students have the highest number of placement offers?",
    "Which students have received an offer but have not joined yet?",
    "Show students who attended placement drives but were not selected.",
    "Which companies have the highest selection rate among eligible students?",
    "Compare the selection rates of Infosys, TCS, Wipro, and Accenture.",
    "Which company has the highest average package for our students?",
    "Which students received packages above INR 10 LPA?",
    "Compare the average package between different departments.",
    "Which students received multiple offers, and from which companies?",
    "Which students are eligible for high-package companies but remain unplaced?",
    "What are the most common reasons students are rejected during placements?",
    "Which technical skills are most common among students who get placed?",
    "Compare the profiles of placed and unplaced students.",
    "Based on our placement data, which students are most likely to succeed in the upcoming placement drives?",
)

EVALUATION_ROLES = (
    "owner",
    "institution_staff",
    "department_staff",
    "cohort_staff",
    "single_student_staff",
    "missing_module_staff",
    "missing_sensitive_staff",
)


def question_variants(question: str) -> tuple[str, ...]:
    typo = question.replace("students", "studnts", 1).replace("attendance", "attendence", 1)
    return (
        question,
        f"Please {question[0].lower()}{question[1:]}",
        typo,
        f"Tamil-la simple-a sollunga: {question}",
    )


assert len(COLLEGE_QUESTIONS) == 120
