"""edvatiq business baseline

Revision ID: 20260730_0001
Revises: 
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260730_0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('industry', sa.Enum('gym', 'salon', 'clinic', 'restaurant', 'retail', 'grocery', 'other', name='industry'), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'trial', 'cancelled', name='organization_status'), nullable=False),
    sa.Column('plan', sa.Enum('trial', 'starter', 'growth', 'business', 'enterprise', name='subscription_plan'), nullable=False),
    sa.Column('enabled_modules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('legal_name', sa.String(length=220), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('contact_email', sa.String(length=200), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('ai_provider', sa.String(length=30), nullable=False),
    sa.Column('ai_model_override', sa.String(length=80), nullable=True),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('categories',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_category_org_name')
    )
    op.create_index(op.f('ix_categories_organization_id'), 'categories', ['organization_id'], unique=False)
    op.create_table('feature_flags',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('flag', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'flag', name='uq_flag_org_key')
    )
    op.create_index(op.f('ix_feature_flags_organization_id'), 'feature_flags', ['organization_id'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=120), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=120), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_organization_id'), 'invoices', ['organization_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('kind', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_job_org_idempotency')
    )
    op.create_index(op.f('ix_jobs_kind'), 'jobs', ['kind'], unique=False)
    op.create_index(op.f('ix_jobs_organization_id'), 'jobs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_jobs_run_at'), 'jobs', ['run_at'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('lab_tests',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('price_paise', sa.Integer(), nullable=False),
    sa.Column('reference_ranges', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_tests_organization_id'), 'lab_tests', ['organization_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=12), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('invoice_sequence', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'code', name='uq_location_org_code')
    )
    op.create_index(op.f('ix_locations_organization_id'), 'locations', ['organization_id'], unique=False)
    op.create_table('membership_plans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('price_paise', sa.BigInteger(), nullable=False),
    sa.Column('joining_fee_paise', sa.BigInteger(), nullable=False),
    sa.Column('benefits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membership_plans_organization_id'), 'membership_plans', ['organization_id'], unique=False)
    op.create_table('payment_events',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('module', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_code'), 'permissions', ['code'], unique=True)
    op.create_index(op.f('ix_permissions_module'), 'permissions', ['module'], unique=False)
    op.create_index(op.f('ix_permissions_organization_id'), 'permissions', ['organization_id'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'name', name='uq_role_org_name')
    )
    op.create_index(op.f('ix_roles_organization_id'), 'roles', ['organization_id'], unique=False)
    op.create_index(op.f('ix_roles_slug'), 'roles', ['slug'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'key', name='uq_setting_org_key')
    )
    op.create_index(op.f('ix_settings_organization_id'), 'settings', ['organization_id'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('razorpay_subscription_id', sa.String(length=120), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('current_period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('current_period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('hashed_password', sa.String(length=300), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('avatar_base64', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('designation', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('action_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'email', name='uq_user_org_email')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('access_scopes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('scope_value', sa.String(length=200), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_scopes_organization_id'), 'access_scopes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_access_scopes_user_id'), 'access_scopes', ['user_id'], unique=False)
    op.create_table('ai_usage',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('tool_calls', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_usage_organization_id'), 'ai_usage', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_usage_user_id'), 'ai_usage', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=True),
    sa.Column('resource_id', sa.String(length=80), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('tool', sa.String(length=120), nullable=True),
    sa.Column('permission', sa.String(length=120), nullable=True),
    sa.Column('rows_affected', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=80), nullable=True),
    sa.Column('device', sa.String(length=200), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('catalog_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('category_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('item_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_sac', sa.String(length=20), nullable=True),
    sa.Column('price_paise', sa.BigInteger(), nullable=False),
    sa.Column('cost_paise', sa.BigInteger(), nullable=False),
    sa.Column('tax_rate_bps', sa.Integer(), nullable=False),
    sa.Column('tax_inclusive', sa.Boolean(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=False),
    sa.Column('track_stock', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'sku', name='uq_catalog_org_sku')
    )
    op.create_index(op.f('ix_catalog_items_category_id'), 'catalog_items', ['category_id'], unique=False)
    op.create_index(op.f('ix_catalog_items_item_type'), 'catalog_items', ['item_type'], unique=False)
    op.create_index(op.f('ix_catalog_items_organization_id'), 'catalog_items', ['organization_id'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('provider', sa.String(length=30), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_organization_id'), 'chat_conversations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_chat_conversations_user_id'), 'chat_conversations', ['user_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('home_location_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('customer_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('joined_on', sa.Date(), nullable=False),
    sa.Column('last_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('whatsapp_consent', sa.Boolean(), nullable=False),
    sa.Column('email_consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['home_location_id'], ['locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'customer_number', name='uq_customer_org_number')
    )
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_home_location_id'), 'customers', ['home_location_id'], unique=False)
    op.create_index(op.f('ix_customers_organization_id'), 'customers', ['organization_id'], unique=False)
    op.create_index(op.f('ix_customers_phone'), 'customers', ['phone'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('uploaded_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('object_key', sa.String(length=600), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_entity_id'), 'documents', ['entity_id'], unique=False)
    op.create_index(op.f('ix_documents_entity_type'), 'documents', ['entity_type'], unique=False)
    op.create_index(op.f('ix_documents_location_id'), 'documents', ['location_id'], unique=False)
    op.create_index(op.f('ix_documents_organization_id'), 'documents', ['organization_id'], unique=False)
    op.create_index(op.f('ix_documents_status'), 'documents', ['status'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('employee_number', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('designation', sa.String(length=120), nullable=True),
    sa.Column('specialties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('salary_paise', sa.BigInteger(), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'employee_number', name='uq_employee_org_number')
    )
    op.create_index(op.f('ix_employees_email'), 'employees', ['email'], unique=False)
    op.create_index(op.f('ix_employees_organization_id'), 'employees', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employees_phone'), 'employees', ['phone'], unique=False)
    op.create_index(op.f('ix_employees_status'), 'employees', ['status'], unique=False)
    op.create_index(op.f('ix_employees_user_id'), 'employees', ['user_id'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('asset_code', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('purchased_on', sa.Date(), nullable=True),
    sa.Column('next_service_on', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_location_id'), 'equipment', ['location_id'], unique=False)
    op.create_index(op.f('ix_equipment_next_service_on'), 'equipment', ['next_service_on'], unique=False)
    op.create_index(op.f('ix_equipment_organization_id'), 'equipment', ['organization_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_organization_id'), 'notifications', ['organization_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('token_hash', sa.String(length=200), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('permission_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('user_permission_overrides',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('permission_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'permission_id', name='uq_user_perm_override')
    )
    op.create_index(op.f('ix_user_permission_overrides_permission_id'), 'user_permission_overrides', ['permission_id'], unique=False)
    op.create_index(op.f('ix_user_permission_overrides_user_id'), 'user_permission_overrides', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('ai_actions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('preview', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('confirmation_token_hash', sa.String(length=100), nullable=True),
    sa.Column('confirmation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_ai_action_org_key')
    )
    op.create_index(op.f('ix_ai_actions_conversation_id'), 'ai_actions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_organization_id'), 'ai_actions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_actions_status'), 'ai_actions', ['status'], unique=False)
    op.create_index(op.f('ix_ai_actions_user_id'), 'ai_actions', ['user_id'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employee_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('service_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['catalog_items.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_customer_id'), 'appointments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_appointments_employee_id'), 'appointments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_appointments_ends_at'), 'appointments', ['ends_at'], unique=False)
    op.create_index(op.f('ix_appointments_location_id'), 'appointments', ['location_id'], unique=False)
    op.create_index(op.f('ix_appointments_organization_id'), 'appointments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_appointments_service_id'), 'appointments', ['service_id'], unique=False)
    op.create_index(op.f('ix_appointments_starts_at'), 'appointments', ['starts_at'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('conversation_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_organization_id'), 'chat_messages', ['organization_id'], unique=False)
    op.create_table('diet_plans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('meals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diet_plans_customer_id'), 'diet_plans', ['customer_id'], unique=False)
    op.create_index(op.f('ix_diet_plans_organization_id'), 'diet_plans', ['organization_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('document_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_organization_id'), 'document_chunks', ['organization_id'], unique=False)
    op.create_table('employee_locations',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employee_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'location_id', name='uq_employee_location')
    )
    op.create_index(op.f('ix_employee_locations_employee_id'), 'employee_locations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_employee_locations_location_id'), 'employee_locations', ['location_id'], unique=False)
    op.create_table('fitness_measurements',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('measured_on', sa.Date(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitness_measurements_customer_id'), 'fitness_measurements', ['customer_id'], unique=False)
    op.create_index(op.f('ix_fitness_measurements_measured_on'), 'fitness_measurements', ['measured_on'], unique=False)
    op.create_index(op.f('ix_fitness_measurements_organization_id'), 'fitness_measurements', ['organization_id'], unique=False)
    op.create_table('gym_classes',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trainer_employee_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gym_classes_location_id'), 'gym_classes', ['location_id'], unique=False)
    op.create_index(op.f('ix_gym_classes_organization_id'), 'gym_classes', ['organization_id'], unique=False)
    op.create_index(op.f('ix_gym_classes_starts_at'), 'gym_classes', ['starts_at'], unique=False)
    op.create_table('memberships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('plan_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('frozen_from', sa.Date(), nullable=True),
    sa.Column('frozen_until', sa.Date(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['membership_plans.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memberships_customer_id'), 'memberships', ['customer_id'], unique=False)
    op.create_index(op.f('ix_memberships_ends_on'), 'memberships', ['ends_on'], unique=False)
    op.create_index(op.f('ix_memberships_location_id'), 'memberships', ['location_id'], unique=False)
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_plan_id'), 'memberships', ['plan_id'], unique=False)
    op.create_index(op.f('ix_memberships_status'), 'memberships', ['status'], unique=False)
    op.create_table('outbound_messages',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('channel', sa.String(length=30), nullable=False),
    sa.Column('recipient', sa.String(length=200), nullable=False),
    sa.Column('template', sa.String(length=120), nullable=True),
    sa.Column('subject', sa.String(length=250), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_outbound_org_idempotency')
    )
    op.create_index(op.f('ix_outbound_messages_customer_id'), 'outbound_messages', ['customer_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_location_id'), 'outbound_messages', ['location_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_organization_id'), 'outbound_messages', ['organization_id'], unique=False)
    op.create_index(op.f('ix_outbound_messages_scheduled_for'), 'outbound_messages', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_outbound_messages_status'), 'outbound_messages', ['status'], unique=False)
    op.create_table('patient_profiles',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('abha_number', sa.String(length=30), nullable=True),
    sa.Column('blood_group', sa.String(length=10), nullable=True),
    sa.Column('emergency_contact', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('medical_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_profiles_abha_number'), 'patient_profiles', ['abha_number'], unique=False)
    op.create_index(op.f('ix_patient_profiles_customer_id'), 'patient_profiles', ['customer_id'], unique=True)
    op.create_index(op.f('ix_patient_profiles_organization_id'), 'patient_profiles', ['organization_id'], unique=False)
    op.create_table('sale_invoices',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('employee_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('invoice_number', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('subtotal_paise', sa.BigInteger(), nullable=False),
    sa.Column('discount_paise', sa.BigInteger(), nullable=False),
    sa.Column('cgst_paise', sa.BigInteger(), nullable=False),
    sa.Column('sgst_paise', sa.BigInteger(), nullable=False),
    sa.Column('igst_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.Column('paid_paise', sa.BigInteger(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_sale_org_idempotency'),
    sa.UniqueConstraint('organization_id', 'invoice_number', name='uq_sale_org_number')
    )
    op.create_index(op.f('ix_sale_invoices_customer_id'), 'sale_invoices', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sale_invoices_employee_id'), 'sale_invoices', ['employee_id'], unique=False)
    op.create_index(op.f('ix_sale_invoices_location_id'), 'sale_invoices', ['location_id'], unique=False)
    op.create_index(op.f('ix_sale_invoices_organization_id'), 'sale_invoices', ['organization_id'], unique=False)
    op.create_index(op.f('ix_sale_invoices_status'), 'sale_invoices', ['status'], unique=False)
    op.create_table('staff_schedules',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('employee_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('starts_at', sa.Time(), nullable=False),
    sa.Column('ends_at', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'location_id', 'weekday', name='uq_staff_schedule_day')
    )
    op.create_index(op.f('ix_staff_schedules_employee_id'), 'staff_schedules', ['employee_id'], unique=False)
    op.create_index(op.f('ix_staff_schedules_location_id'), 'staff_schedules', ['location_id'], unique=False)
    op.create_index(op.f('ix_staff_schedules_organization_id'), 'staff_schedules', ['organization_id'], unique=False)
    op.create_table('stock_levels',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('reorder_level_milli', sa.BigInteger(), nullable=False),
    sa.Column('batch_number', sa.String(length=80), nullable=False),
    sa.Column('expires_on', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('location_id', 'item_id', 'batch_number', name='uq_stock_location_item_batch')
    )
    op.create_index(op.f('ix_stock_levels_item_id'), 'stock_levels', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_levels_location_id'), 'stock_levels', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_levels_organization_id'), 'stock_levels', ['organization_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('assigned_to_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_assigned_to_user_id'), 'tasks', ['assigned_to_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_customer_id'), 'tasks', ['customer_id'], unique=False)
    op.create_index(op.f('ix_tasks_due_at'), 'tasks', ['due_at'], unique=False)
    op.create_index(op.f('ix_tasks_location_id'), 'tasks', ['location_id'], unique=False)
    op.create_index(op.f('ix_tasks_organization_id'), 'tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('trainer_assignments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trainer_employee_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trainer_assignments_customer_id'), 'trainer_assignments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_trainer_assignments_organization_id'), 'trainer_assignments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_trainer_assignments_trainer_employee_id'), 'trainer_assignments', ['trainer_employee_id'], unique=False)
    op.create_table('workout_plans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('trainer_employee_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('schedule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trainer_employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plans_customer_id'), 'workout_plans', ['customer_id'], unique=False)
    op.create_index(op.f('ix_workout_plans_organization_id'), 'workout_plans', ['organization_id'], unique=False)
    op.create_table('allergies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('substance', sa.String(length=160), nullable=False),
    sa.Column('reaction', sa.String(length=250), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allergies_organization_id'), 'allergies', ['organization_id'], unique=False)
    op.create_index(op.f('ix_allergies_patient_id'), 'allergies', ['patient_id'], unique=False)
    op.create_table('class_bookings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('gym_class_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['gym_class_id'], ['gym_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('gym_class_id', 'customer_id', name='uq_class_customer')
    )
    op.create_index(op.f('ix_class_bookings_customer_id'), 'class_bookings', ['customer_id'], unique=False)
    op.create_index(op.f('ix_class_bookings_gym_class_id'), 'class_bookings', ['gym_class_id'], unique=False)
    op.create_index(op.f('ix_class_bookings_organization_id'), 'class_bookings', ['organization_id'], unique=False)
    op.create_table('encounters',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('patient_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('appointment_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('practitioner_employee_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('chief_complaint', sa.Text(), nullable=True),
    sa.Column('clinical_notes', sa.Text(), nullable=True),
    sa.Column('assessment', sa.Text(), nullable=True),
    sa.Column('plan', sa.Text(), nullable=True),
    sa.Column('follow_up_on', sa.Date(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_profiles.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['practitioner_employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['signed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encounters_appointment_id'), 'encounters', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_encounters_location_id'), 'encounters', ['location_id'], unique=False)
    op.create_index(op.f('ix_encounters_organization_id'), 'encounters', ['organization_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_index(op.f('ix_encounters_practitioner_employee_id'), 'encounters', ['practitioner_employee_id'], unique=False)
    op.create_index(op.f('ix_encounters_status'), 'encounters', ['status'], unique=False)
    op.create_table('gym_check_ins',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('membership_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['membership_id'], ['memberships.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membership_id', 'checked_in_at', name='uq_membership_checkin_time')
    )
    op.create_index(op.f('ix_gym_check_ins_checked_in_at'), 'gym_check_ins', ['checked_in_at'], unique=False)
    op.create_index(op.f('ix_gym_check_ins_customer_id'), 'gym_check_ins', ['customer_id'], unique=False)
    op.create_index(op.f('ix_gym_check_ins_location_id'), 'gym_check_ins', ['location_id'], unique=False)
    op.create_index(op.f('ix_gym_check_ins_membership_id'), 'gym_check_ins', ['membership_id'], unique=False)
    op.create_index(op.f('ix_gym_check_ins_organization_id'), 'gym_check_ins', ['organization_id'], unique=False)
    op.create_table('sale_lines',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('item_name', sa.String(length=180), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=True),
    sa.Column('hsn_sac', sa.String(length=20), nullable=True),
    sa.Column('quantity_milli', sa.BigInteger(), nullable=False),
    sa.Column('unit_price_paise', sa.BigInteger(), nullable=False),
    sa.Column('discount_paise', sa.BigInteger(), nullable=False),
    sa.Column('tax_rate_bps', sa.Integer(), nullable=False),
    sa.Column('tax_paise', sa.BigInteger(), nullable=False),
    sa.Column('total_paise', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sale_invoices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sale_lines_invoice_id'), 'sale_lines', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_sale_lines_item_id'), 'sale_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_sale_lines_organization_id'), 'sale_lines', ['organization_id'], unique=False)
    op.create_table('sale_payments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('invoice_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('amount_paise', sa.BigInteger(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('idempotency_key', sa.String(length=120), nullable=False),
    sa.Column('received_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sale_invoices.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['received_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_payment_org_idempotency')
    )
    op.create_index(op.f('ix_sale_payments_invoice_id'), 'sale_payments', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_sale_payments_organization_id'), 'sale_payments', ['organization_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('stock_level_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('movement_type', sa.String(length=30), nullable=False),
    sa.Column('quantity_delta_milli', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('reference_type', sa.String(length=40), nullable=True),
    sa.Column('reference_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('performed_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['catalog_items.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['stock_level_id'], ['stock_levels.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_item_id'), 'stock_movements', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_location_id'), 'stock_movements', ['location_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_organization_id'), 'stock_movements', ['organization_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_performed_by_user_id'), 'stock_movements', ['performed_by_user_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_reference_id'), 'stock_movements', ['reference_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_stock_level_id'), 'stock_movements', ['stock_level_id'], unique=False)
    op.create_table('diagnoses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('encounter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('code', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('ai_suggested', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnoses_encounter_id'), 'diagnoses', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_diagnoses_organization_id'), 'diagnoses', ['organization_id'], unique=False)
    op.create_table('lab_orders',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('encounter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('test_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_id'], ['lab_tests.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_orders_encounter_id'), 'lab_orders', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_organization_id'), 'lab_orders', ['organization_id'], unique=False)
    op.create_index(op.f('ix_lab_orders_status'), 'lab_orders', ['status'], unique=False)
    op.create_index(op.f('ix_lab_orders_test_id'), 'lab_orders', ['test_id'], unique=False)
    op.create_table('prescriptions',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('encounter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ai_drafted', sa.Boolean(), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescriptions_encounter_id'), 'prescriptions', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_prescriptions_organization_id'), 'prescriptions', ['organization_id'], unique=False)
    op.create_table('vitals',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('encounter_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitals_encounter_id'), 'vitals', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_vitals_organization_id'), 'vitals', ['organization_id'], unique=False)
    op.create_table('dispenses',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('location_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prescription_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dispensed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispensed_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dispensed_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dispenses_location_id'), 'dispenses', ['location_id'], unique=False)
    op.create_index(op.f('ix_dispenses_organization_id'), 'dispenses', ['organization_id'], unique=False)
    op.create_index(op.f('ix_dispenses_prescription_id'), 'dispenses', ['prescription_id'], unique=False)
    op.create_table('lab_results',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('order_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['lab_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lab_results_order_id'), 'lab_results', ['order_id'], unique=True)
    op.create_index(op.f('ix_lab_results_organization_id'), 'lab_results', ['organization_id'], unique=False)
    op.create_table('prescription_items',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('organization_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('prescription_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('medicine_item_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('medicine_name', sa.String(length=200), nullable=False),
    sa.Column('dosage', sa.String(length=100), nullable=False),
    sa.Column('frequency', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.String(length=100), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['medicine_item_id'], ['catalog_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prescription_id'], ['prescriptions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prescription_items_organization_id'), 'prescription_items', ['organization_id'], unique=False)
    op.create_index(op.f('ix_prescription_items_prescription_id'), 'prescription_items', ['prescription_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prescription_items_prescription_id'), table_name='prescription_items')
    op.drop_index(op.f('ix_prescription_items_organization_id'), table_name='prescription_items')
    op.drop_table('prescription_items')
    op.drop_index(op.f('ix_lab_results_organization_id'), table_name='lab_results')
    op.drop_index(op.f('ix_lab_results_order_id'), table_name='lab_results')
    op.drop_table('lab_results')
    op.drop_index(op.f('ix_dispenses_prescription_id'), table_name='dispenses')
    op.drop_index(op.f('ix_dispenses_organization_id'), table_name='dispenses')
    op.drop_index(op.f('ix_dispenses_location_id'), table_name='dispenses')
    op.drop_table('dispenses')
    op.drop_index(op.f('ix_vitals_organization_id'), table_name='vitals')
    op.drop_index(op.f('ix_vitals_encounter_id'), table_name='vitals')
    op.drop_table('vitals')
    op.drop_index(op.f('ix_prescriptions_organization_id'), table_name='prescriptions')
    op.drop_index(op.f('ix_prescriptions_encounter_id'), table_name='prescriptions')
    op.drop_table('prescriptions')
    op.drop_index(op.f('ix_lab_orders_test_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_status'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_organization_id'), table_name='lab_orders')
    op.drop_index(op.f('ix_lab_orders_encounter_id'), table_name='lab_orders')
    op.drop_table('lab_orders')
    op.drop_index(op.f('ix_diagnoses_organization_id'), table_name='diagnoses')
    op.drop_index(op.f('ix_diagnoses_encounter_id'), table_name='diagnoses')
    op.drop_table('diagnoses')
    op.drop_index(op.f('ix_stock_movements_stock_level_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_reference_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_performed_by_user_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_organization_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_location_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_item_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_sale_payments_organization_id'), table_name='sale_payments')
    op.drop_index(op.f('ix_sale_payments_invoice_id'), table_name='sale_payments')
    op.drop_table('sale_payments')
    op.drop_index(op.f('ix_sale_lines_organization_id'), table_name='sale_lines')
    op.drop_index(op.f('ix_sale_lines_item_id'), table_name='sale_lines')
    op.drop_index(op.f('ix_sale_lines_invoice_id'), table_name='sale_lines')
    op.drop_table('sale_lines')
    op.drop_index(op.f('ix_gym_check_ins_organization_id'), table_name='gym_check_ins')
    op.drop_index(op.f('ix_gym_check_ins_membership_id'), table_name='gym_check_ins')
    op.drop_index(op.f('ix_gym_check_ins_location_id'), table_name='gym_check_ins')
    op.drop_index(op.f('ix_gym_check_ins_customer_id'), table_name='gym_check_ins')
    op.drop_index(op.f('ix_gym_check_ins_checked_in_at'), table_name='gym_check_ins')
    op.drop_table('gym_check_ins')
    op.drop_index(op.f('ix_encounters_status'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_practitioner_employee_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_organization_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_location_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_appointment_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_class_bookings_organization_id'), table_name='class_bookings')
    op.drop_index(op.f('ix_class_bookings_gym_class_id'), table_name='class_bookings')
    op.drop_index(op.f('ix_class_bookings_customer_id'), table_name='class_bookings')
    op.drop_table('class_bookings')
    op.drop_index(op.f('ix_allergies_patient_id'), table_name='allergies')
    op.drop_index(op.f('ix_allergies_organization_id'), table_name='allergies')
    op.drop_table('allergies')
    op.drop_index(op.f('ix_workout_plans_organization_id'), table_name='workout_plans')
    op.drop_index(op.f('ix_workout_plans_customer_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_index(op.f('ix_trainer_assignments_trainer_employee_id'), table_name='trainer_assignments')
    op.drop_index(op.f('ix_trainer_assignments_organization_id'), table_name='trainer_assignments')
    op.drop_index(op.f('ix_trainer_assignments_customer_id'), table_name='trainer_assignments')
    op.drop_table('trainer_assignments')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_organization_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_location_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_due_at'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_customer_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_assigned_to_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_stock_levels_organization_id'), table_name='stock_levels')
    op.drop_index(op.f('ix_stock_levels_location_id'), table_name='stock_levels')
    op.drop_index(op.f('ix_stock_levels_item_id'), table_name='stock_levels')
    op.drop_table('stock_levels')
    op.drop_index(op.f('ix_staff_schedules_organization_id'), table_name='staff_schedules')
    op.drop_index(op.f('ix_staff_schedules_location_id'), table_name='staff_schedules')
    op.drop_index(op.f('ix_staff_schedules_employee_id'), table_name='staff_schedules')
    op.drop_table('staff_schedules')
    op.drop_index(op.f('ix_sale_invoices_status'), table_name='sale_invoices')
    op.drop_index(op.f('ix_sale_invoices_organization_id'), table_name='sale_invoices')
    op.drop_index(op.f('ix_sale_invoices_location_id'), table_name='sale_invoices')
    op.drop_index(op.f('ix_sale_invoices_employee_id'), table_name='sale_invoices')
    op.drop_index(op.f('ix_sale_invoices_customer_id'), table_name='sale_invoices')
    op.drop_table('sale_invoices')
    op.drop_index(op.f('ix_patient_profiles_organization_id'), table_name='patient_profiles')
    op.drop_index(op.f('ix_patient_profiles_customer_id'), table_name='patient_profiles')
    op.drop_index(op.f('ix_patient_profiles_abha_number'), table_name='patient_profiles')
    op.drop_table('patient_profiles')
    op.drop_index(op.f('ix_outbound_messages_status'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_scheduled_for'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_organization_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_location_id'), table_name='outbound_messages')
    op.drop_index(op.f('ix_outbound_messages_customer_id'), table_name='outbound_messages')
    op.drop_table('outbound_messages')
    op.drop_index(op.f('ix_memberships_status'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_plan_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_location_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_ends_on'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_customer_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_gym_classes_starts_at'), table_name='gym_classes')
    op.drop_index(op.f('ix_gym_classes_organization_id'), table_name='gym_classes')
    op.drop_index(op.f('ix_gym_classes_location_id'), table_name='gym_classes')
    op.drop_table('gym_classes')
    op.drop_index(op.f('ix_fitness_measurements_organization_id'), table_name='fitness_measurements')
    op.drop_index(op.f('ix_fitness_measurements_measured_on'), table_name='fitness_measurements')
    op.drop_index(op.f('ix_fitness_measurements_customer_id'), table_name='fitness_measurements')
    op.drop_table('fitness_measurements')
    op.drop_index(op.f('ix_employee_locations_location_id'), table_name='employee_locations')
    op.drop_index(op.f('ix_employee_locations_employee_id'), table_name='employee_locations')
    op.drop_table('employee_locations')
    op.drop_index(op.f('ix_document_chunks_organization_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_diet_plans_organization_id'), table_name='diet_plans')
    op.drop_index(op.f('ix_diet_plans_customer_id'), table_name='diet_plans')
    op.drop_table('diet_plans')
    op.drop_index(op.f('ix_chat_messages_organization_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_starts_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_service_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_organization_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_location_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_ends_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_employee_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_customer_id'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_ai_actions_user_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_status'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_organization_id'), table_name='ai_actions')
    op.drop_index(op.f('ix_ai_actions_conversation_id'), table_name='ai_actions')
    op.drop_table('ai_actions')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_permission_overrides_user_id'), table_name='user_permission_overrides')
    op.drop_index(op.f('ix_user_permission_overrides_permission_id'), table_name='user_permission_overrides')
    op.drop_table('user_permission_overrides')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_organization_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_equipment_organization_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_next_service_on'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_location_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_employees_user_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_status'), table_name='employees')
    op.drop_index(op.f('ix_employees_phone'), table_name='employees')
    op.drop_index(op.f('ix_employees_organization_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_email'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_documents_status'), table_name='documents')
    op.drop_index(op.f('ix_documents_organization_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_location_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_type'), table_name='documents')
    op.drop_index(op.f('ix_documents_entity_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_phone'), table_name='customers')
    op.drop_index(op.f('ix_customers_organization_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_home_location_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_chat_conversations_user_id'), table_name='chat_conversations')
    op.drop_index(op.f('ix_chat_conversations_organization_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_catalog_items_organization_id'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_item_type'), table_name='catalog_items')
    op.drop_index(op.f('ix_catalog_items_category_id'), table_name='catalog_items')
    op.drop_table('catalog_items')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_ai_usage_user_id'), table_name='ai_usage')
    op.drop_index(op.f('ix_ai_usage_organization_id'), table_name='ai_usage')
    op.drop_table('ai_usage')
    op.drop_index(op.f('ix_access_scopes_user_id'), table_name='access_scopes')
    op.drop_index(op.f('ix_access_scopes_organization_id'), table_name='access_scopes')
    op.drop_table('access_scopes')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_settings_organization_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_roles_slug'), table_name='roles')
    op.drop_index(op.f('ix_roles_organization_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_organization_id'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_module'), table_name='permissions')
    op.drop_index(op.f('ix_permissions_code'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_table('payment_events')
    op.drop_index(op.f('ix_membership_plans_organization_id'), table_name='membership_plans')
    op.drop_table('membership_plans')
    op.drop_index(op.f('ix_locations_organization_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_lab_tests_organization_id'), table_name='lab_tests')
    op.drop_table('lab_tests')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_at'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_organization_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_kind'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_invoices_organization_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_feature_flags_organization_id'), table_name='feature_flags')
    op.drop_table('feature_flags')
    op.drop_index(op.f('ix_categories_organization_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
