import React, { useEffect, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { useAuth } from "@/contexts/AuthContext";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { ArrowLeft, CalendarBlank, CurrencyInr, IdentificationCard, MapPin, NotePencil, ShieldCheck, User } from "@phosphor-icons/react";
import { toast } from "sonner";
import { useGetEmployeeProfileQuery } from "@/store/api/workspaceApi";
import { QUERY_POLICIES } from "@/store/api/queryPolicies";
import { ProfileBackLink } from "@/components/entities/EntityProfile";
import { EmptyState, PageShell, Surface } from "@/components/system";
import { useUpdateEmployeeMutation } from "@/features/team/teamApi";

const weekdays = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"];

export default function EmployeeProfile() {
  const { employeeId } = useParams(); const { can } = useAuth();
  const { data, error } = useGetEmployeeProfileQuery(employeeId, QUERY_POLICIES.reference); const [editing, setEditing] = useState(false); const [form, setForm] = useState({}); const [updateEmployee] = useUpdateEmployeeMutation();
  useEffect(() => { if (data?.employee && !editing) setForm(data.employee); }, [data, editing]);
  const save = async () => { const payload = { employeeId, first_name: form.first_name, last_name: form.last_name, phone: form.phone || null, email: form.email || null, designation: form.designation || null, specialties: form.specialties || [], joining_date: form.joining_date || null, status: form.status, location_ids: form.location_ids, version: form.version }; if (data.capabilities.view_compensation) payload.salary_paise = form.salary_paise ?? null; try { await updateEmployee(payload).unwrap(); toast.success("Employee updated"); setEditing(false); } catch (requestError) { toast.error(requestError?.data?.detail || "Could not update employee"); } };
  if (error) return <PageShell><Empty title={error.status === 403 ? "Access restricted" : "Employee unavailable"} copy={error.data?.detail || "Could not load employee"} /></PageShell>;
  if (!data) return <PageShell><div className="h-72 animate-pulse rounded-2xl bg-secondary" /></PageShell>;
  const employee = data.employee;
  const hasWork = Boolean(data.appointments?.length || data.sales?.length);
  return <PageShell className="reveal" size="standard">
    <ProfileBackLink fallback="/app/team" className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft />Back</ProfileBackLink>
    <Surface className="flex flex-col justify-between gap-5 p-5 sm:p-6 lg:flex-row lg:items-center"><div className="flex min-w-0 gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center rounded-2xl bg-primary font-display text-2xl text-primary-foreground sm:h-16 sm:w-16 sm:text-3xl">{employee.first_name[0]}</div><div className="min-w-0"><div className="font-mono text-xs text-muted-foreground">{employee.employee_number}</div><h1 className="mt-1 truncate font-display text-2xl font-semibold sm:text-3xl">{employee.first_name} {employee.last_name}</h1><div className="mt-2 text-sm text-muted-foreground">{employee.designation || "Team member"} / <span className="capitalize">{employee.status}</span></div></div></div>{data.capabilities.manage && <Button className="self-start rounded-xl lg:self-auto" onClick={() => setEditing(true)}><NotePencil className="mr-2" />Edit employee</Button>}</Surface>
    {(data.capabilities.view_appointments || data.capabilities.view_sales) && <div className="grid sm:grid-cols-3 gap-4">{data.capabilities.view_appointments && <><Metric icon={CalendarBlank} label="Appointments" value={data.metrics.appointment_count} /><Metric icon={User} label="Completed" value={data.metrics.completed_appointments} /></>}{data.capabilities.view_sales && <Metric icon={CurrencyInr} label="Attributed sales" value={money(data.metrics.sales_paise)} />}</div>}
    <Tabs defaultValue="overview"><TabsList className="premium-scrollbar h-auto max-w-full justify-start overflow-x-auto rounded-xl"><TabsTrigger value="overview">Overview</TabsTrigger>{hasWork && <TabsTrigger value="work">Work history</TabsTrigger>}<TabsTrigger value="schedule">Schedule</TabsTrigger>{data.capabilities.view_account && <TabsTrigger value="access">Login & access</TabsTrigger>}</TabsList>
      <TabsContent value="overview" className="mt-5 grid items-start gap-5 lg:grid-cols-2"><Panel title="Employment"><Detail icon={IdentificationCard} label="Designation" value={employee.designation} /><Detail label="Joined" value={employee.joining_date ? new Date(employee.joining_date).toLocaleDateString("en-IN") : null} />{data.capabilities.view_compensation && <Detail label="Monthly salary" value={employee.salary_paise != null ? money(employee.salary_paise) : "Not set"} />}<div className="mt-4 flex flex-wrap gap-2">{employee.specialties?.map((item) => <span key={item} className="rounded-full bg-secondary px-3 py-1 text-xs">{item}</span>)}</div></Panel><Panel title="Locations">{data.locations.length ? data.locations.map((location) => <div key={location.id} className="flex gap-3 border-b py-3 last:border-0"><MapPin className="text-accent" /><div><div className="font-medium">{location.name}</div><div className="text-xs text-muted-foreground">{location.city || "No city"}{location.is_primary ? " / Primary" : ""}</div></div></div>) : <EmptyState variant="inline" icon={MapPin} title="No locations assigned" description="Assign a location before scheduling work." />}</Panel></TabsContent>
      {hasWork && <TabsContent value="work" className="mt-5 grid items-start gap-5 lg:grid-cols-2">{data.appointments?.length > 0 && <Panel title="Recent appointments">{data.appointments.map((item) => <Row key={item.id} title={item.status} meta={new Date(item.starts_at).toLocaleString("en-IN")} value={item.notes} />)}</Panel>}{data.sales?.length > 0 && <Panel title="Recent sales">{data.sales.map((item) => <Row key={item.id} title={item.invoice_number} meta={new Date(item.created_at).toLocaleDateString("en-IN")} value={money(item.total_paise)} />)}</Panel>}</TabsContent>}
      <TabsContent value="schedule" className="mt-5"><Panel title="Weekly availability">{data.schedules.length ? <div className="grid gap-3 sm:grid-cols-2">{data.schedules.map((item) => <div key={item.id} className="rounded-xl border p-4"><div className="font-medium">{weekdays[item.weekday] || `Day ${item.weekday}`}</div><div className="mt-1 text-sm text-muted-foreground">{item.starts_at.slice(0, 5)} - {item.ends_at.slice(0, 5)}</div></div>)}</div> : <EmptyState variant="inline" icon={CalendarBlank} title="No schedule configured" description="Set availability before assigning appointments." />}</Panel></TabsContent>
      {data.capabilities.view_account && <TabsContent value="access" className="mt-5"><Panel title="Account access">{data.account ? <><Detail icon={ShieldCheck} label="Login email" value={data.account.email} /><Detail label="Account" value={data.account.is_active ? "Active" : "Disabled"} /><Detail label="Last login" value={data.account.last_login ? new Date(data.account.last_login).toLocaleString("en-IN") : "Never"} />{can("roles.manage") && <Button asChild variant="outline" className="mt-3 rounded-xl"><Link to="/app/access">Manage roles and locations</Link></Button>}</> : <EmptyState variant="inline" icon={ShieldCheck} title="No application access" description="This employee has a business profile without a login account." />}</Panel></TabsContent>}
    </Tabs>
    <Dialog open={editing} onOpenChange={setEditing}><DialogContent className="sm:max-w-2xl"><DialogHeader><DialogTitle className="font-display text-3xl">Edit employee</DialogTitle></DialogHeader><div className="grid sm:grid-cols-2 gap-4"><Field label="First name"><Input value={form.first_name || ""} onChange={set("first_name")} /></Field><Field label="Last name"><Input value={form.last_name || ""} onChange={set("last_name")} /></Field><Field label="Phone"><Input value={form.phone || ""} onChange={set("phone")} /></Field><Field label="Email"><Input value={form.email || ""} onChange={set("email")} /></Field><Field label="Designation"><Input value={form.designation || ""} onChange={set("designation")} /></Field>{data.capabilities.view_compensation && <Field label="Monthly salary (INR)"><Input type="number" value={form.salary_paise == null ? "" : form.salary_paise / 100} onChange={(event) => setForm({ ...form, salary_paise: event.target.value ? Math.round(Number(event.target.value) * 100) : null })} /></Field>}<Field label="Joining date"><Input type="date" value={form.joining_date || ""} onChange={set("joining_date")} /></Field><Field label="Status"><select className="w-full h-10 border rounded-xl bg-background px-3" value={form.status || "active"} onChange={set("status")}>{["active", "on_leave", "inactive"].map((value) => <option key={value}>{value}</option>)}</select></Field><div className="sm:col-span-2"><Label>Locations</Label><div className="grid sm:grid-cols-2 gap-2 mt-2">{data.available_locations.map((location) => <label key={location.id} className="border rounded-xl p-3 text-sm flex gap-2"><input type="checkbox" checked={form.location_ids?.includes(location.id)} onChange={(event) => setForm({ ...form, location_ids: event.target.checked ? [...(form.location_ids || []), location.id] : form.location_ids.filter((id) => id !== location.id) })} />{location.name}</label>)}</div></div><Button onClick={save} className="sm:col-span-2 rounded-xl">Save employee</Button></div></DialogContent></Dialog>
  </PageShell>;
  function set(key) { return (event) => setForm({ ...form, [key]: event.target.value }); }
}
function Metric({ icon: Icon, label, value }) { return <Surface className="p-5"><Icon className="text-accent" /><div className="mt-3 font-display text-3xl">{value}</div><div className="mt-1 text-xs text-muted-foreground">{label}</div></Surface>; }
function Panel({ title, children }) { return <Surface className="p-5"><h2 className="mb-4 font-display text-xl font-semibold sm:text-2xl">{title}</h2>{children}</Surface>; }
function Detail({ icon: Icon, label, value }) { return <div className="py-2 flex gap-3">{Icon && <Icon className="text-muted-foreground" />}<div><div className="overline">{label}</div><div className="text-sm mt-1">{value || "Not provided"}</div></div></div>; }
function Row({ title, meta, value }) { return <div className="py-3 border-b last:border-0 flex justify-between gap-3"><div><div className="font-medium capitalize">{title}</div><div className="text-xs text-muted-foreground">{meta}</div></div><div className="text-sm">{value}</div></div>; }
function Field({ label, children }) { return <div className="space-y-2"><Label>{label}</Label>{children}</div>; }
function Empty({ title, copy }) { return <EmptyState variant="page" icon={User} title={title} description={copy} />; }
function money(value) { return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format((value || 0) / 100); }
