import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { zodResolver } from "@hookform/resolvers/zod";
import { useForm } from "react-hook-form";
import api from "@/lib/api";
import { AuthLayout } from "@/pages/Login";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage, FormRootError } from "@/components/ui/form";
import PasswordStrength from "@/components/PasswordStrength";
import { applyApiErrors, forgotPasswordRequestSchema, FORM_OPTIONS, resetPasswordSchema } from "@/lib/validation";
import { CheckCircle, Key } from "@phosphor-icons/react";
import { toast } from "sonner";

export default function ForgotPassword() {
  const navigate = useNavigate(); const [step, setStep] = useState("request");
  const form = useForm({ resolver: zodResolver(step === "request" ? forgotPasswordRequestSchema : resetPasswordSchema), defaultValues: { email: "", org_slug: "", code: "", new_password: "", confirm: "" }, ...FORM_OPTIONS });
  const { clearErrors, control, formState, handleSubmit, setError, watch } = form;
  const emailValue = watch("email"); const passwordValue = watch("new_password"); const confirmation = watch("confirm");
  const request = handleSubmit(async (values) => { clearErrors("root.server"); try { await api.post("/auth/password/forgot", { email: values.email, org_slug: values.org_slug || null }); clearErrors(); setStep("reset"); toast.success("If the account exists, a reset code has been sent"); } catch (error) { const normalized = applyApiErrors(error, setError, { fallback: "Could not request a reset code" }); if (!Object.keys(normalized.fieldErrors).length) setError("root.server", { type: "server", message: normalized.message }); } });
  const reset = handleSubmit(async (values) => { clearErrors("root.server"); try { await api.post("/auth/password/reset", { email: values.email, org_slug: values.org_slug || null, code: values.code, new_password: values.new_password }); toast.success("Password updated. Please sign in again"); navigate("/login"); } catch (error) { const normalized = applyApiErrors(error, setError, { fallback: "Password could not be reset" }); if (!Object.keys(normalized.fieldErrors).length) setError("root.server", { type: "server", message: normalized.message }); } });
  return <AuthLayout eyebrow="Account recovery" title={step === "request" ? "Reset your password." : "Create a new password."}><Form {...form}>{step === "request" ? <form noValidate onSubmit={request} className="space-y-4 mt-6"><div className="w-11 h-11 rounded-2xl bg-accent/10 text-accent grid place-items-center"><Key size={22} /></div><p className="text-sm text-muted-foreground">Enter your email and we will send a six-digit reset code.</p><RecoveryField control={control} name="email" label="Work email"><Input type="email" autoComplete="email" /></RecoveryField><RecoveryField control={control} name="org_slug" label="Business ID" hint="Only needed if this email is connected to more than one business."><Input autoComplete="organization" /></RecoveryField><FormRootError error={formState.errors.root?.server} /><Button type="submit" className="w-full" loading={formState.isSubmitting} loadingText="Sending...">Send reset code</Button></form> : <form noValidate onSubmit={reset} className="space-y-4 mt-6"><div className="flex gap-2 items-center text-sm text-muted-foreground"><CheckCircle className="text-emerald-700 shrink-0" />Code sent to {emailValue}</div><RecoveryField control={control} name="code" label="Six-digit code"><Input inputMode="numeric" autoComplete="one-time-code" maxLength={6} className="text-center text-xl tracking-[.35em] font-mono" /></RecoveryField><RecoveryField control={control} name="new_password" label="New password"><Input type="password" autoComplete="new-password" maxLength={128} /></RecoveryField><PasswordStrength password={passwordValue || ""} compact /><RecoveryField control={control} name="confirm" label="Confirm password"><Input type="password" autoComplete="new-password" maxLength={128} /></RecoveryField>{confirmation && <p className={`text-xs ${confirmation === passwordValue ? "text-emerald-700" : "text-red-600"}`}>{confirmation === passwordValue ? "Passwords match" : "Passwords do not match"}</p>}<FormRootError error={formState.errors.root?.server} /><Button type="submit" className="w-full" loading={formState.isSubmitting} loadingText="Updating password...">Set new password</Button></form>}</Form><p className="text-sm text-center mt-5"><Link to="/login" className="text-foreground font-medium">Back to sign in</Link></p></AuthLayout>;
}
function RecoveryField({ control, name, label, hint, children }) { return <FormField control={control} name={name} render={({ field }) => <FormItem><FormLabel>{label}</FormLabel><FormControl>{React.cloneElement(children, { ...field, value: field.value ?? "", onChange: (event) => field.onChange(name === "code" ? event.target.value.replace(/\D/g, "") : name === "org_slug" ? event.target.value.toLowerCase() : event) })}</FormControl>{hint && <FormDescription>{hint}</FormDescription>}<FormMessage /></FormItem>} />; }
