import React, { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import api from "@/lib/api";
import { AuthLayout } from "@/pages/Login";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import PasswordStrength, { isPasswordAcceptable } from "@/components/PasswordStrength";
import { CheckCircle, Key } from "@phosphor-icons/react";
import { toast } from "sonner";

export default function ForgotPassword() {
  const navigate = useNavigate(); const [step, setStep] = useState("request"); const [loading, setLoading] = useState(false);
  const [form, setForm] = useState({ email: "", org_slug: "", code: "", new_password: "", confirm: "" });
  const set = (key) => (event) => setForm({ ...form, [key]: key === "code" ? event.target.value.replace(/\D/g, "") : event.target.value });
  const request = async (event) => { event.preventDefault(); setLoading(true); try { await api.post("/auth/password/forgot", { email: form.email, org_slug: form.org_slug || null }); setStep("reset"); toast.success("If the account exists, a reset code has been sent"); } catch (error) { toast.error(error.response?.data?.detail || "Could not request a reset code"); } finally { setLoading(false); } };
  const passwordReady = isPasswordAcceptable(form.new_password);
  const reset = async (event) => { event.preventDefault(); if (!passwordReady) return toast.error("Please choose a stronger password"); if (form.new_password !== form.confirm) return toast.error("Passwords do not match"); setLoading(true); try { await api.post("/auth/password/reset", { email: form.email, org_slug: form.org_slug || null, code: form.code, new_password: form.new_password }); toast.success("Password updated. Please sign in again"); navigate("/login"); } catch (error) { toast.error(error.response?.data?.detail || "Password could not be reset"); } finally { setLoading(false); } };
  return <AuthLayout eyebrow="Account recovery" title={step === "request" ? "Reset your password." : "Create a new password."}>{step === "request" ? <form onSubmit={request} className="space-y-4 mt-6"><div className="w-11 h-11 rounded-2xl bg-accent/10 text-accent grid place-items-center"><Key size={22} /></div><p className="text-sm text-muted-foreground">Enter your email and we will send a six-digit reset code.</p><Field label="Work email"><Input type="email" autoComplete="email" value={form.email} onChange={set("email")} required /></Field><Field label="Business ID" hint="Only needed if this email is connected to more than one business."><Input value={form.org_slug} onChange={set("org_slug")} /></Field><Button className="w-full" disabled={loading}>{loading ? "Sending..." : "Send reset code"}</Button></form> : <form onSubmit={reset} className="space-y-4 mt-6"><div className="flex gap-2 items-center text-sm text-muted-foreground"><CheckCircle className="text-emerald-700 shrink-0" />Code sent to {form.email}</div><Field label="Six-digit code"><Input inputMode="numeric" autoComplete="one-time-code" maxLength={6} pattern="[0-9]{6}" className="text-center text-xl tracking-[.35em] font-mono" value={form.code} onChange={set("code")} required /></Field><Field label="New password"><Input type="password" autoComplete="new-password" minLength={10} value={form.new_password} onChange={set("new_password")} required /><PasswordStrength password={form.new_password} compact /></Field><Field label="Confirm password"><Input type="password" autoComplete="new-password" minLength={10} value={form.confirm} onChange={set("confirm")} required />{form.confirm && <p className={`text-xs mt-1 ${form.confirm === form.new_password ? "text-emerald-700" : "text-red-600"}`}>{form.confirm === form.new_password ? "Passwords match" : "Passwords do not match"}</p>}</Field><Button className="w-full" disabled={loading || form.code.length !== 6 || !passwordReady || form.confirm !== form.new_password}>{loading ? "Updating password..." : "Set new password"}</Button></form>}<p className="text-sm text-center mt-5"><Link to="/login" className="text-foreground font-medium">Back to sign in</Link></p></AuthLayout>;
}
function Field({ label, hint, children }) { return <div className="space-y-2"><Label>{label}</Label>{children}{hint && <p className="text-xs text-muted-foreground">{hint}</p>}</div>; }
